sudo: required
dist: trusty
language: java

services:
  - docker

install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to heroku
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

  # install ecs-deploy
  - sudo apt-get update
  - sudo apt-get install jq -y
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee -a /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy

after_success:
    # install AWS CLI
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    # login to ECR
    - eval $(aws ecr get-login --no-include-email --region us-west-2)

script:
  # build docker image
  - mvn clean install
  - docker build -t truthtree:test .
  - docker tag truthtree:test registry.heroku.com/truthtree/web
  - docker tag truthtree:test 869798252720.dkr.ecr.us-west-2.amazonaws.com/truthtree:latest

deploy:
  provider: heroku
  script:
    # push to heroku
    docker push registry.heroku.com/truthtree/web;
    heroku container:release web --app=truthtree;
  on:
    branch: develop
  provider: script
  script:
    #docker tag truthtree:test 869798252720.dkr.ecr.us-west-2.amazonaws.com/truthtree:latest
    docker push 869798252720.dkr.ecr.us-west-2.amazonaws.com/truthtree:latest;
    ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $IMAGE_REPO_URL:latest;
  on:
    branch: feature/pull_frontend_from_docker